apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zulip.fullname" . }}-cm
data:
    zulip.conf: |-
        [application_server]
        http_only = true
        [loadbalancer]
        ips = 0.0.0.0/0
